
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2021"
name = "serialport-detect-binding"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
pin-project-lite = "0.2"
futures = "0.3"
serialport-detect = { path = "../../", features = ["napi"] }
napi-derive = "3.0.0"
napi = { version = "3.0.0", default-features = false, features = [
"tokio",
"tokio_rt",
]}
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
